import "@emotion/react";
import type { Metadata } from "next";
import { Geist_Mono, Merienda } from "next/font/google";
import Link from "next/link";
import "../styles/globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merienda.variable} ${geistMono.variable} antialiased`}>
        <nav className="space-x-6 text-xl">
          <Link href="/">Back to home</Link> <Link href="/users">Users</Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
